#!/bin/bash
set -e
# environment for GitHub CI
if [ -d "/usr/lib/jvm/java-17-openjdk-amd64/" ]; then
  export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
fi

DIR=$(pwd)

function run_for_java {
  cd $1
  ./gradlew --no-daemon clean :${1}-core:build :${1}-${2}:build
  cd $DIR
  docker-compose build ${1}-${2}
  docker-compose up ${1}-${2}
}

function run_for_vertx {
  cd $1
  ./gradlew --no-daemon clean :${1}-core:build :${1}-${2}:shadowJar
  cd $DIR
  docker-compose build ${1}-${2}
  docker-compose up ${1}-${2}
}

if [ "$1" = "pizzeria" ]; then
  case "$2" in
    boot|core|servlet|webflux)
      run_for_java $1 $2
      ;;
    vertx)
      run_for_vertx $1 $2
      ;;
    ui)
      docker-compose build ${1}-${2}
      docker-compose up ${1}-${2}
      ;;
    build)
      cd pizzeria
      ./gradlew --no-daemon clean pizzeria-core:build pizzeria-servlet:build pizzeria-webflux:build pizzeria-boot:build pizzeria-vertx:shadowJar
      cd -
      ;;
    all)
      cd pizzeria
      ./gradlew --no-daemon clean pizzeria-core:build pizzeria-servlet:build pizzeria-webflux:build pizzeria-boot:build pizzeria-vertx:shadowJar
      cd $DIR
      docker-compose build pizzeria-servlet pizzeria-webflux pizzeria-boot pizzeria-vertx
      docker-compose up -d pizzeria-servlet pizzeria-webflux pizzeria-boot pizzeria-vertx nginx pizzeria-ui
      ;;
    *)
      echo Nothing to do for $1 $2
      ;;
  esac
fi
