-- Ingredients

insert into pizzeria.Ingredient (name, price, protected) values ('ail', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('ananas', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('anchois', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('artichauts', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('aubergines grillees', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('bacon', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('bacon fume', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('boeuf', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('boeuf epicee', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('capres', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('champignons', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('cheddar', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('chorizo', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('creme fraiche', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('emince de boeuf', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('emmental', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fourme d\'ambert aop', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage a raclette', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage de chevre', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage fondu', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage grimbergen', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fromage rapee', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('fruits de mer', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('gorgonzola', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('jambon', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('jambon italien', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('lardons fumes', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('merguez', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('mozzarella', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('oeuf', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('oignons', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('oignons rouges', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('olives', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('origan', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('pepperoni', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('persil', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('piments forts', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('piments verts', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poivrons', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poivron vert', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('pommes de terre', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('porc epicee', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poulet frit', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poulet fume', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poulet grille', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('poulet kebab (halal)', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('provolone', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('pulled pork', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('reblochon', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce a l\'ail', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce au poivre', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce barbecue', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce chili thai', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce curry douce', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('sauce tomate', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('saumon fume', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('thon', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('tomate', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('tomates fraiches', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('viande de veau fume', 1, true);
insert into pizzeria.Ingredient (name, price, protected) values ('viande hachee', 1, true);
